# Cloudflare Pages configuration for imgbase admin UI
name = "imgbase-admin"
compatibility_date = "2024-06-20"

# Pages specific configuration
pages_build_output_dir = "admin/.vercel/output/static"