# Cloudflare Pages configuration for imgbase admin UI
name = "imgbase-admin"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

# Pages specific configuration
pages_build_output_dir = "admin/out"

# Note: Build command must be configured in Cloudflare Dashboard
# Build command: cd admin && npm install && npm run cf:build